version: "3"

services:
    frontend:
        build:
            context: .
            args:
                NEXT_PUBLIC_BRAND: ${NEXT_PUBLIC_BRAND:-antey}
        container_name: frontend
        restart: unless-stopped
        tty: true
        environment:
            NEXT_PUBLIC_BRAND: ${NEXT_PUBLIC_BRAND:-antey}
        expose:
            - "3000"

        networks:
            - traefik
        labels:
            - traefik.enable=true
            - traefik.http.routers.frontend.rule=Host(`front.netvol.org`)
            - traefik.http.routers.frontend.entrypoints=web
            - traefik.http.services.frontend.loadbalancer.server.port=3000

networks:
    traefik:
        external: true